# Site settings
title: umt.world
author:
  name: Uriah Marc Todoroff
  email: um.todoroff@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Uriah Marc Todoroff.
baseurl: ""
url: "" # http://example.com
twitter_username: theinvertedform
github_username:  theinvertedform
permalink: /:slugified_categories/:title

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

toc:
  ordered_list: true

# Collections
collections:
collections_dir: collections
#   tags:
#     name: true
#  authors:
#    output: false
#    permalink: authors#/:short_name

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
        #toc: "true"
      #category: "blog"
      #      toc: true
      #  - scope:
      #      path: "_posts/film criticism/"
      #      type: "posts"
      #    values:
      #      layout: "post"
      #      category: "film criticism"
      #      permalink: reviews/:title
      #  - scope:
      #      path: "_posts/art criticism/"
      #      type: "posts"
      #    values:
      #      layout: "post"
      #      category: "art criticism"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "collections/blog/_posts/"
    values:
      category: "Blog"
      #  - scope:
      #      path: ""
      #      type: "authors"
      #    values:
      #      layout: "author"
      #      url: "/authors#/{{ short_name }}"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - TODO.md
