# Site settings
title: umt.world
description: A hypertext project by Uriah Marc Todoroff.
author:
  name: Uriah Marc Todoroff
  email: um.todoroff@gmail.com
twitter:
  username: theinvertedform
  card: summary
github_username:  theinvertedform
baseurl: ""
url: "https://umt.world"
permalink: /:title
logo: /assets/images/logo.png
iis_slider_array: []
repository: theinvertedform/umt.world

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-pandoc
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-github-metadata

    #feed:
    #  categories:
    #    newsletter:
    #      path: "/newsletter.atom"
    #posts_limit: 20
    #

    #last-modified-at:
    #  date-format: "%b %e, %Y"

toc:
  ordered_list: false

last-modified-at:
  date-format: "%b %-d, %Y"

markdown: Pandoc

pandoc:
  format: html5
  extensions:
    - csl: "assets/csl/chicago-fullnote-bibliography.csl"
    - bibliography: "collections/bibliography.bib"
    - citeproc
    #- lua-filter: "_plugins/metadata-headings.lua" # this needs to come after citeproc
    - from: "markdown+gfm_auto_identifiers"
    - section_divs

# Collections
collections:
  diary:
    permalink: "/diaries#:year-:month-:day"
 # blog:
 #   permalink: "/blog#:year-:month-:day"
  podcast:
    permalink: "/podcast#:title"
  stories:
    output: true
    permalink: "/:title"
  interviews:
    output: true
    permalink: "/interviews/:title"
  essays:
    output: true
    permalink: ":title"
  film:
    output: true
    permalink: "/films/:title-:year"
  reviews:
    output: true
    permalink: "/reviews/:title"
 # newsletter:
 #   output: true
 #   permalink: "/newsletter/:year#:month"
collections_dir: "collections/"
#   tags:
#     name: true
#  authors:
#    output: false
#    permalink: authors#/:short_name

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "post"

# Google analytics
google_analytics: G-5NHX2XP9H3

# sass

backlinks:
  excluded_backlink_pages:
    - "index.html"
    - "index"
    - "/index"
    - "changes.html"
    - "404.html"
    - "feed.xml"
    - "sitemap.xml"
    - "robots.txt"
    - "tags.html"
    - "tags"
    - "/tags"
  excluded_id_elements:
    - "#sidebar"
    - ".sidebar-links"
  context:
    chars_before: 100
    chars_after: 100
  output_dir: "_data/backlinks"
  debug: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower.json
  - bower_components/
  - collections/archive
  - collections/pdfs
  - collections/notes
  - collections/publications
  - collections/_novels
  - collections/.gitignore
  - collections/.git
  - collections/_films/reviews.csv
