# Site settings
title: umt.world
author:
  name: Uriah Marc Todoroff
  email: um.todoroff@gmail.com
description: This is the personal website of Uriah Marc Todoroff.
baseurl: ""
url: "https://umt.world" # http://example.com
twitter_username: theinvertedform
github_username:  theinvertedform
permalink: /:title
logo: assets/images/logo.png

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-pandoc

    #feed:
    #  categories:
    #    newsletter:
    #      path: "/newsletter.atom"
    #posts_limit: 20
    #

    #last-modified-at:
    #  date-format: "%b %e, %Y"

toc:
  ordered_list: false

markdown: Pandoc

pandoc:
  format: html5
  extensions:
    - csl: "assets/csl/chicago-author-date.csl"
    - bibliography: "assets/bibliography.bib"
    - citeproc

# Collections
collections:
  blog:
    permalink: "/blog#:year-:month-:day"
  podcast:
    permalink: "/podcast#:title"
  philosophy:
    output: true
    permalink: "/:title"
  reviews:
    permalink: "reviews/:slug"
    output: true
collections_dir: "collections/"
#   tags:
#     name: true
#  authors:
#    output: false
#    permalink: authors#/:short_name

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "collections"
      type: "documents"
    values:
      layout: "post"
  - scope:
      path: "collections/_reviews/films/"
    values:
      itemtype: "film review"
        #- scope:
        #    path: "collections/reviews/films"
        #  values:
        #    permalink: "/:slugified_categories/#:title"
        #    category: "film review"
        # - scope:
        #     path: "collections/podcast/_posts"
        #   values:
        #     permalink: "/podcast#:title"

# Google analytics
google_analytics: G-5NHX2XP9H3

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - TODO.md
