# Site settings
title: umt.world
description: A hypertext project by Uriah Marc Todoroff
author:
  name: Uriah Marc Todoroff
  email: umt@umt.world
twitter:
  username: theinvertedform
  card: summary
github_username:  theinvertedform
baseurl: ""
url: "https://umt.world"
permalink: /:title
logo: /assets/images/logo.png
repository: theinvertedform/umt.world

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-pandoc
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-github-metadata

toc:
  ordered_list: false

last-modified-at:
  date-format: "%b %-d, %Y"

markdown: Pandoc

pandoc:
  format: html5
  extensions:
    - csl: "assets/csl/chicago-fullnote-bibliography.csl"
    - bibliography: "collections/bibliography.bib"
    - citeproc
    - lua-filter: "_plugins/metadata-headings.lua" # this needs to come after citeproc
    - from: "markdown+gfm_auto_identifiers"
    - section_divs

# Collections
collections_dir: "collections/"
collections:
  books:
    output: true
    permalink: "/books/:title"
  criticism:
    output: true
    permalink: "/criticism/:title"
  culture:
    output: true
    permalink: "/culture/:title"
  fiction:
    output: true
    permalink: "/fiction/:title"
  interviews:
    output: true
    permalink: "/interviews/:title"
  newsletter:
    output: true
    permalink: "/newsletter/:year/:month/:day"
  personal:
    output: true
    permalink: "/:title"
  podcast:
    output: false
    permalink: "/podcast#:title"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "post"

google_analytics: G-5NHX2XP9H3

backlinks:
  excluded_backlink_pages:
    - "index.html"
    - "index"
    - "/index"
    - "changes.html"
    - "404.html"
    - "feed.xml"
    - "sitemap.xml"
    - "robots.txt"
    - "tags.html"
    - "tags"
    - "/tags"
  excluded_id_elements:
    - "#sidebar"
    - ".sidebar-links"
  context:
    chars_before: 100
    chars_after: 100
  output_dir: "_data/backlinks"
  debug: true

include:
  - node_modules

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower.json
  - bower_components/
  - collections/archive
  - collections/pdfs
  - collections/notes
  - collections/publications
  - collections/_fiction/
  - collections/.gitignore
  - collections/.git
  - _culture/film-diary/
  - package-lock.json
  - package.json
