categories:
  - name: articles
  - name: reviews
  - name: blog
  - name: features
  - name: editorial
tags:
  - name: montreal
  - name: marxism
  - name: theory
  - name: communism
  - name: meta
  - name: russia
  - name: china
authors:
  - name: Karl Marx
    bio: The father of revolutionary theory.
    short_name: marx
